blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.views import BlogListView, BlogCreateView, BlogDeleteView, BlogUpdateView, toggle_activity, BlogDetailView

from blog.apps import BlogConfig

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='blog_list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('update/<int:pk>/', BlogUpdateView.as_view(), name='blog_update'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete'),
    path('activity/<int:pk>/', toggle_activity, name='toggle_activity'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('service.urls', namespace='service')),
                  path('users/', include('users.urls', namespace='users')),
                  path('blog/', include('blog.urls', namespace='blog'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

service/urls.py
from django.urls import path
from service.apps import ServiceConfig
from service.views import (ClientListView, ClientDetailView, ClientCreateView, ClientUpdateView,
                           ClientDeleteView, MessageListView, MessageDetailView, MessageCreateView, MessageUpdateView,
                           MessageDeleteView, ContactsView,
                           MailingView, MailingDetailView, MailingCreateView, MailingUpdateView, MailingDeleteView)
app_name = ServiceConfig.name


urlpatterns = [
    path('', ClientListView.as_view(), name='client_list'),
    path('contacts/', ContactsView.as_view(), name="contact_list"),
    path('client/<int:pk>/', ClientDetailView.as_view(), name='client_detail'),
    path('client/create/', ClientCreateView.as_view(), name='client_form'),
    path('client/<int:pk>/update/', ClientUpdateView.as_view(), name='client_update'),
    path('client/<int:pk>/delete/', ClientDeleteView.as_view(), name='client_delete'),
    path('message/', MessageListView.as_view(), name='message_list'),
    path('message/<int:pk>/', MessageDetailView.as_view(), name='message_detail'),
    path('message/create/', MessageCreateView.as_view(), name='message_form'),
    path('message/<int:pk>/update/', MessageUpdateView.as_view(), name='message_update'),
    path('message/<int:pk>/delete/', MessageDeleteView.as_view(), name='message_delete'),
    path('mailing/', MailingView.as_view(), name='mailing_list'),
    path('mailing/<int:pk>/', MailingDetailView.as_view(), name='mailing_detail'),
    path('mailing/create/', MailingCreateView.as_view(), name='mailing_form'),
    path('mailing/<int:pk>/update/', MailingUpdateView.as_view(), name='mailing_update'),
    path('mailing/<int:pk>/delete/', MailingDeleteView.as_view(), name='mailing_delete'),
]

service/models.py
from django.db import models

from users.models import User

NULLABLE = {'blank': True, 'null': True}


class Client(models.Model):
    email = models.EmailField(max_length=100, verbose_name='электронная почта клиента')
    first_name = models.CharField(max_length=100, **NULLABLE, verbose_name='имя клиента')
    last_name = models.CharField(max_length=100, **NULLABLE, verbose_name='фамилия клиента')
    comment = models.TextField(**NULLABLE, verbose_name='комментарий клиента')
    owner = models.ForeignKey(User, default=True, on_delete=models.CASCADE, verbose_name='пользователь')

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    class Meta:
        verbose_name = 'клиент'
        verbose_name_plural = 'клиенты'


class Message(models.Model):
    subject = models.CharField(max_length=150, verbose_name='тема сообщения')
    text = models.TextField(**NULLABLE, verbose_name='текст сообщения')
    picture = models.ImageField(upload_to='service/', **NULLABLE, verbose_name='картинка сообщения')
    owner = models.ForeignKey(User, default=True, on_delete=models.CASCADE, verbose_name='пользователь')

    def __str__(self):
        return f'{self.subject}'

    class Meta:
        verbose_name = 'сообщение'
        verbose_name_plural = 'сообщения'
        permissions = [
            ('cannot_change_message', 'Не может изменять сообщения'),
        ]


class Mailing(models.Model):
    time_sending = models.DateTimeField(verbose_name='дата и время отправки')
    time_end = models.DateTimeField(verbose_name='дата и время окончания')
    periodicity_chose = [
        ('once a week', 'один раз в неделю'),
        ('everyday', 'каждый день'),
        ('once a month', 'один раз в месяц'),
    ]
    periodicity = models.CharField(max_length=100, choices=periodicity_chose, verbose_name='периодичность')
    status_chose = [
        ('created', 'создана'),
        ('launched', 'запущена'),
        ('completed', 'завершена'),
    ]
    status = models.CharField(max_length=100, choices=status_chose, verbose_name='статус')
    clients = models.ManyToManyField(Client, verbose_name='клиенты')
    message = models.ForeignKey(Message, on_delete=models.CASCADE, **NULLABLE, verbose_name='сообщение')
    owner = models.ForeignKey(User, default=True, on_delete=models.CASCADE, verbose_name='пользователь')

    def __str__(self):
        return f'{self.time_sending}'

    class Meta:
        verbose_name = 'рассылка'
        verbose_name_plural = 'рассылки'
        permissions = [
            ('can_view_mailing', 'Может просматривать рассылки'),
            ('can_disable_mailing', 'Может отключать рассылки'),
            ('cannot_edit_mailing', 'Не может редактировать рассылки'),
            ('cannot_manage_mailing', 'Не может управлять списком рассылок'),
            ('cannot_change_mailing', 'Не может создавать рассылки'),
        ]


class Attempt(models.Model):
    time_attempt = models.DateTimeField(auto_now_add=True, verbose_name='время попытки')
    status_chose = [
        ('successful', 'успешно'),
        ('unsuccessful', 'не успешно'),
    ]
    status = models.CharField(max_length=100, choices=status_chose, verbose_name='статус попытки')
    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, verbose_name='рассылка')
    answer = models.TextField(**NULLABLE, verbose_name='ответ сервера')

    def __str__(self):
        return f'{self.time_attempt} {self.status}'

    class Meta:
        verbose_name = 'попытка'
        verbose_name_plural = 'попытки'


class Contacts(models.Model):
    city = models.CharField(max_length=50, verbose_name="Страна")
    identity_nalog_number = models.IntegerField(verbose_name="ИНН")
    address = models.TextField(verbose_name="Адрес")
    slug = models.CharField(max_length=255, verbose_name="URL", **NULLABLE)

    def __str__(self):
        return f"{self.city} {self.identity_nalog_number} {self.address}"

    class Meta:
        verbose_name = "Контакт"
        verbose_name_plural = "Контакты"

service/forms.py
from django.db.models import BooleanField
from django.forms import ModelForm, forms
from service.models import Client, Message, Mailing


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class ClientForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Client
        exclude = ('last_name ', 'comment', 'owner')


class ClientModeratorForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Client
        exclude = ('last_name ', 'comment', 'owner')


class MessageForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Message
        exclude = ("picture",)


class MessageModeratorForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Message
        exclude = ("picture",)


class MailingForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Mailing
        exclude = ("message",)


class MailingModeratorForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Mailing
        exclude = ("message",)

service/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.exceptions import PermissionDenied
from django.forms import inlineformset_factory, ModelForm

from service.forms import MailingModeratorForm, MessageModeratorForm, MessageForm, MailingForm, ClientForm, \
    StyleFormMixin
from service.models import Client, Message, Mailing, Attempt, Contacts
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView


class ClientListView(LoginRequiredMixin, ListView):
    model = Client
    fields = ['email', 'first_name', 'last_name']
    template_name = 'service/client_list.html'
    extra_context = {'title': 'Клиенты'}

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    success_url = reverse_lazy('service:client_list')

    def get_queryset(self):
        return Client.objects.filter(owner=self.request.user)


class ClientDetailView(LoginRequiredMixin, DetailView):
    model = Client
    fields = ['email', 'first_name', 'last_name']
    template_name = 'service/client_detail.html'
    success_url = reverse_lazy('service:client_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        client_item = self.get_object()
        context['title'] = client_item.first_name
        return context


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    fields = ['email', 'first_name', 'last_name']
    template_name = 'service/client_form.html'
    success_url = reverse_lazy('service:client_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Создание клиента'
        return context

    def form_valid(self, form):
        client = form.save()
        user = self.request.user
        client.owner = user
        client.save()
        return super().form_valid(form)

    def get_queryset(self):
        return Client.objects.all()


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    model = Client
    fields = ['email', 'first_name', 'last_name']
    template_name = 'service/client_form.html'
    success_url = reverse_lazy('service:client_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        client_item = self.get_object()
        context['title'] = client_item.first_name
        return context


class ClientDeleteView(LoginRequiredMixin, DeleteView):
    model = Client
    fields = ['email', 'first_name', 'last_name', 'comment']
    template_name = 'service/client_confirm_delete.html'
    success_url = reverse_lazy('service:client_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        client_item = self.get_object()
        context['title'] = client_item.first_name
        return context


class MessageListView(LoginRequiredMixin, ListView):
    model = Message
    fields = ['subject', 'text', 'picture']
    template_name = 'service/message_list.html'
    extra_context = {'title': 'Напишите сообщение'}

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def get_queryset(self):
        return Message.objects.filter(owner=self.request.user)


class MessageDetailView(LoginRequiredMixin, DetailView):
    model = Message
    fields = ['subject', 'text', 'picture']
    template_name = 'service/message_detail.html'
    success_url = reverse_lazy('service:message_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        message_item = self.get_object()
        context['title'] = message_item.subject
        return context


class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    fields = ['subject', 'text', 'picture']
    template_name = 'service/message_form.html'
    success_url = reverse_lazy('service:message_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Создание сообщения'
        return context

    def form_valid(self, form):
        message = form.save()
        user = self.request.user
        message.owner = user
        message.save()
        return super().form_valid(form)


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    model = Message
    fields = ['subject', 'text', 'picture']
    template_name = 'service/message_form.html'
    success_url = reverse_lazy('service:message_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        message_item = self.get_object()
        context['title'] = message_item.subject
        return context

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner:
            return MessageForm
        if user.groups.filter(name='Manager').exists():
            return MessageModeratorForm
        raise PermissionDenied


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    model = Message
    fields = ['subject', 'text', 'picture']
    template_name = 'service/message_confirm_delete.html'
    success_url = reverse_lazy('service:message_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        message_item = self.get_object()
        context['title'] = message_item.subject
        return context


class MailingView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = Mailing
    fields = ['time_sending', 'time_end', 'periodicity', 'status', 'clients']
    template_name = 'service/mailing_list.html'
    extra_context = {'title': 'Рассылка'}
    permission_required = 'service.view_maling'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def get_queryset(self):
        return Mailing.objects.filter(owner=self.request.user)


class MailingDetailView(LoginRequiredMixin, DetailView):
    model = Mailing
    fields = ['time_sending', 'time_end', 'periodicity', 'status', 'clients']
    template_name = 'service/mailing_detail.html'
    success_url = reverse_lazy('service:mailing_form')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        mailing_item = self.get_object()
        context['title'] = mailing_item.time_sending
        return context


class MailingCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Mailing
    fields = ['time_sending', 'time_end', 'periodicity', 'status', 'clients']
    template_name = 'service/mailing_form.html'
    success_url = reverse_lazy('service:mailing_list')
    permission_required = 'service.add_maling'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Создание рассылки'
        return context

    def form_valid(self, form):
        client = form.save()
        user = self.request.user
        client.owner = user
        client.save()
        return super().form_valid(form)

    def get_queryset(self):
        return Mailing.objects.all()


class MailingUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Mailing
    fields = ['time_sending', 'time_end', 'periodicity', 'status', 'clients']
    template_name = 'service/mailing_form.html'
    permission_required = 'service.change_maling'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        mailing_item = self.get_object()
        context['title'] = mailing_item.time_sending
        return context

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner:
            return MailingForm
        if user.groups.filter(name='Manager').exists():
            return MailingModeratorForm
        raise PermissionDenied


class MailingDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Mailing
    fields = ['time_sending', 'time_end', 'periodicity', 'status', 'clients']
    template_name = 'service/mailing_confirm_delete.html'
    success_url = reverse_lazy('service:mailing_list')
    permission_required = 'service.delete_maling'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        mailing_item = self.get_object()
        context['title'] = mailing_item.time_sending
        return context


class AttemptView(LoginRequiredMixin, ListView):
    model = Attempt
    fields = ['status']
    template_name = 'service/attempt_list.html'
    extra_context = {'title': 'Попытки'}


class ContactsView(LoginRequiredMixin, ListView):
    model = Contacts
    fields = ['name', 'phone', 'email']
    extra_context = {'title': 'Контакты'}
    template_name = 'service/contact_list.html'

service/templates/service/attempt_list.html
{% extends 'service/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-3 pb-md-3 mx-auto text-center">
    <h1 class="display-4">Магазин</h1>
    <p class="lead">{{ title }}</p>
</div>
<form method="post" action="" class="form-floating">
    {% csrf_token %}
    <div class="row">
        <div class="row row-cols-1 row-cols-md-2 g-4">
            {% for object in object_list|slice:5 %}
            <div class="col-4">
                <div class="card mb-6 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">
                            {{object.name|title}}</h4>
                        <div class="card-body">
                            <h1 class="card-title pricing-card-title">$ {{object.status_chose}}</h1>
                            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                            </ul>
                            <a type="button" class="btn btn-lg btn-block btn-outline-primary"
                               href="{% url 'service:client_detail' object.pk %}">
                                Подробнее
                            </a>
                            <button type="button" class="btn btn-lg btn-block btn-outline-primary">Оформить заказ
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</form>
{% endblock %}

service/templates/service/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Эта страница создана потом и кровью</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          crossorigin="anonymous">
</head>
<body>

{% include 'service/includes/inc_main.html'%}

{% block content %}


{% endblock %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
</body>
</html>

service/templates/service/client_confirm_delete.html
{% extends 'service/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-8">{{ title }}</h1>
</div>
<main>
    <div class="album py-3 bg-body-tertiary">
        <div class="container text-center">
            <div class="row row-cols-1 row-cols-sm-1 row-cols-md-2 g-3">
                    <div class="col-12">
                        <div class="row">
                            <div class="col-8">
                                <div class="card">
                                    <div class="card-body">
                                        <form method="post" enctype="multipart/form-data">
                                            {% csrf_token %}
                                            <p> Хотите удалить запись "{{ object.first_name }}"? </p>
                                            <button type="submit" class="btn btn-lg btn-block btn-success">Подтвердить</button>
                                        </form>
                                        <a href="{% url 'service:client_list' %}" class="btn btn-lg btn-block btn-danger">Отмена</a>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
            </div>
        </div>
    </div>
</main>

{% endblock %}

service/templates/service/client_detail.html
{% extends 'service/base.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ object.first_name|title }}</h1>
</div>
<main>
    <div class="album py-3 bg-body-tertiary">
        <div class="container text-center">
            <div class="row row-cols-1 row-cols-sm-1 row-cols-md-2 g-3">
                <div class="col">
                    <p class="card shadow-sm">
                        <img class="card-img-top" src="{{ object.emile }}" alt="Фотографии нет">
                    </p>
                </div>
                <div class="col-5 text-md-start">
                    {{ object.comment|truncatechars:20 }}
                    <p>
                        <a href="{% url 'service:client_list' %}"
                           class="btn btn-primary justify-content-md-center my-5">Клиент, созданный {{object.owner}}</a>
                    </p>
                    <div class="btn-group">
                        <a class="btn btn-lg btn-primary" href="{% url 'service:client_list' %}"
                           role="button">Назад</a>
                    </div>
                </div>
            </div>

        </div>
    </div>
</main>

{% endblock %}

service/templates/service/client_list.html
{% extends 'service/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-3 pb-md-3 mx-auto text-center">
    <h1 class="display-4">Клиенты</h1>
</div>
<form method="post" action="" class="form-floating">
    {% csrf_token %}
        <a type="button" class="btn btn-lg btn-block btn-outline-primary"
                                    href="{% url 'service:client_form' %}">
                                    Добавить запись</a>
    <div class="row">
        <div class="row row-cols-1 row-cols-md-2 g-4">
            {% for object in object_list|slice:5 %}
            <div class="col-4">
                <div class="card mb-6 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">
                            {{object.email}}</h4>
                        <div class="card-body">
                            <h1 class="card-title pricing-card-title"> {{object.first_name}}</h1>
                            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                            </ul>
                            <a type="button" class="btn btn-lg btn-block btn-outline-primary"
                               href="{% url 'service:client_detail' object.pk %}">
                                Подробнее
                            </a>
                            <a type="button" class="btn btn-lg btn-block btn-outline-warning"
                               href="{% url 'service:client_update' object.pk %}">
                                Изменить
                            </a>
                            <a type="button" class="btn btn-lg btn-block btn-outline-danger"
                               href="{% url 'service:client_delete' object.pk %}">
                                Удалить
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</form>
{% endblock %}

service/templates/service/contact_list.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"  crossorigin="anonymous">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'service:contact_list' %}">Контакты</a>
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>{{ object.country }}</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>{{ object.inn }}</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>{{ object.address }}</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Контактный телефон" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Наверх</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Тут тоже наверх</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</body>
</html>

service/templates/service/mailing_list.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          crossorigin="anonymous">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'service:message_list' %}">Блог</a>

    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Рассылка</h1>
    <p class="lead">{{ title }}</p>
</div>
<form method="post" action="" class="form-floating">
    {% csrf_token %}
    <a type="button" class="btn btn-lg btn-block btn-outline-primary"
       href="{% url 'service:mailing_form' %}">
        Добавить запись</a>
    <div class="btn-group">
        <a class="btn btn-lg btn-primary" href="{% url 'service:client_list' %}"
           role="button">Назад</a>
    </div>
    <div class="row">
        <div class="row row-cols-1 row-cols-md-2 g-4">
            {% for object in object_list %}
            <div class="col-4">
                <div class="card mb-6 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">
                            {{object.subject|title}}</h4>
                        <div class="card-body">
                            <h1 class="card-title pricing-card-title"></h1>
                            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                            </ul>
                            <a type="button" class="btn btn-lg btn-block btn-outline-primary"
                               href="{% url 'service:mailing_detail' object.pk %}">
                                Подробнее
                            </a>
                            <a type="button" class="btn btn-lg btn-block btn-outline-warning"
                               href="{% url 'service:mailing_update' object.pk %}">
                                Изменить
                            </a>
                            <a type="button" class="btn btn-lg btn-block btn-outline-danger"
                               href="{% url 'service:mailing_delete' object.pk %}">
                                Удалить
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</form>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
</body>
</html>