blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.views import BlogListView, BlogCreateView, BlogDeleteView, BlogUpdateView, toggle_activity, BlogDetailView

from blog.apps import BlogConfig

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='blog_list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('update/<int:pk>/', BlogUpdateView.as_view(), name='blog_update'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete'),
    path('activity/<int:pk>/', toggle_activity, name='toggle_activity'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('service.urls', namespace='service')),
                  path('users/', include('users.urls', namespace='users')),
                  path('blog/', include('blog.urls', namespace='blog'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

from service.models import Client, Mailing

NULLABLE = {'blank': True, 'null': True}


class Blog(models.Model):
    title = models.CharField(max_length=100, verbose_name='Заголовок')
    content = models.TextField(verbose_name="Контент")
    picture = models.ImageField(upload_to='blog/', **NULLABLE)
    is_active = models.BooleanField(default=True)
    number_of_views = models.PositiveIntegerField(default=0, verbose_name="Количество просмотров")
    date_of_publication = models.DateTimeField(auto_now_add=True, verbose_name="Дата публикации")
    client = models.ForeignKey(Client, verbose_name="Клиент", on_delete=models.SET_NULL, **NULLABLE, )
    mailing = models.ForeignKey(Mailing, verbose_name="Рассылки", on_delete=models.SET_NULL, **NULLABLE, )

    def __str__(self):
        return f'{self.title}, {self.number_of_views}, {self.date_of_publication}'

    class Meta:
        verbose_name = 'Блог'
        verbose_name_plural = 'Блоги'

blog/forms.py
from django.db.models import BooleanField
from django.forms import ModelForm

from blog.models import Blog


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class BlogForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Blog
        fields = ('title', 'text', 'image')

blog/views.py
from django.core.exceptions import PermissionDenied
from django.shortcuts import get_object_or_404, redirect
from pytils.translit import slugify
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, DeleteView, UpdateView, DetailView

from blog.models import Blog
from blog.utils import get_cache_mailing_active, get_mailing_count_from_cache, get_cache_unique_quantity


class BlogListView(ListView):
    model = Blog
    template_name = 'blog/blog_list.html'
    extra_context = {'title': 'Блог'}

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['mailing_quantity_active'] = get_cache_mailing_active()
        context['mailing_quantity'] = get_mailing_count_from_cache()
        context['clients_unique_quantity'] = get_cache_unique_quantity()
        context['records'] = Blog.objects.order_by('?')[:3]
        return context


class BlogDetailView(DetailView):
    """Класс, заменяющий функцию products_detail (FBV на CBV)"""
    model = Blog

    def get_object(self, queryset=None):
        """Метод для подсчета к-ва просмотров страницы"""
        self.object = super().get_object()
        self.object.views_counter += 1
        self.object.save()
        return self.object


class BlogCreateView(CreateView):
    model = Blog
    fields = ['title', 'content', 'picture', 'is_active', 'number_of_views']
    template_name = 'blog/blog_form.html'
    success_url = reverse_lazy('blog:blog_list')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Добавить запись в блог'
        return context

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()
        return super().form_valid(form)


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ("name", 'description', 'photo', 'views_counter')
    success_url = reverse_lazy('blog:blog_list')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.name)
            new_mat.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:blog_detail', args=[self.kwargs.get('pk')])


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:blog_list')

    def get_object(self, queryset=None):
        """Метод для определения доступа к удалению только своих записей"""
        self.object = super().get_object(queryset)
        if self.request.user == self.object.owner or self.request.user.groups.filter(name='moderator').exists():
            return self.object
        raise PermissionDenied


def toggle_activity(request, pk):
    """Функция-контроллер для изменения статуса активности товара"""
    blog_item = get_object_or_404(Blog, pk=pk)
    if blog_item.is_published:
        blog_item.is_published = False
    else:
        blog_item.is_published = True
    blog_item.save()
    return redirect(reverse('blog:blog_list'))

blog/templates/blog/blog_confirm_delete.html
{% extends 'blog/blog_list.html' %}
{% block content%}
<div class="container">
    <div class="row">
        <div class="col-6">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <p class="card-text">Точно удаляем {{ blog.title }} ?</p>
                    <div class="card-body">
                        {% csrf_token %}
                    </div>
                    <button type="submit" class="btn btn-danger">
                        Удалить
                    </button>
                    <a class="btn btn-primary" href="{% url 'blog:blog_list' %}"
                       role="button">Отменить удаление</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'blog/blog_list.html' %}
{% load my_tags %}
<!--Подключаем файл my_tags, чтобы можно было выводить фото -->
{% block content%}
<!--Шаблон для вывода товара по одному-->
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            <div class="col">
                <div class="card shadow-sm">
                    <img src="{{ blog.picture|my_media }}">
                    <div class="card-body">
                        <p class="card-text">Заголовок: {{ blog.title }}</p>
                        <p class="card-text">Текст записи: {{ blog.content }}</p>
                        <p class="card-text">Дата записи: {{ blog.date_of_publication }}</p>
                        <p class="card-text">Опубликовано: {{ blog.is_active }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-primary" href="{% url 'blog:blog_list' %}"
                                   role="button">Назад</a>
                            </div>
                            <small class="text-body-secondary">Никому не скажем твой айпи</small>
                        </div>
                        <div class="card-footer">
                            Просмотры: {{ blog.number_of_views }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock%}

blog/templates/blog/blog_form.html
{% extends 'blog/blog_list.html' %}
{% block content%}
<div class="container">
    <div class="row">
        <div class="col-6">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </div>
                    <button type="submit" class="btn btn-primary">
                        {% if blog %}
                            Сохранить
                        {% else %}
                            Создать
                        {% endif %}
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'service/base.html' %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="fw-light"> Это БЛОГ </h1>
    <p class="lead text-body-secondary">Тут надо писать. Ударение на второй слог.</p>
    <p class="lead">{{ title }}</p>
    <p>
        <a class="btn btn-primary" href="{% url 'blog:blog_create' %}"
           role="button">Создать заметку</a>
    </p>
</div>
<div class="container">
    <div class="row text-left">
        <h3>Активных рассылок на данный момент: {{mailing_quantity_active}}</h3>
        <h3>Всего рассылок на данный момент: {{mailing_quantity}}</h3>
        <h3>Уникальных клиентов на данный момент: {{clients_unique_quantity}}</h3>
        {% for record in records %}
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Название</td>
                            <td>{{ record.title }}</td>
                        </tr>
                        <tr>
                            <td class="w-25">Описание</td>
                            <td>{{ record.description }}</td>
                        </tr>
                        <tr>
                            <td class="w-25">Дата создания</td>
                            <td>{{ record.created_at }}</td>
                        </tr>
                        <tr>
                            <td class="w-25">Дата редактирования</td>
                            <td>{{ record.updated_at }}</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

{% for object in blog_list %}
<div class="col">
    <div class="card shadow-sm">
        <div class="card-body">
            <p class="card-text">{{ object.name }}</p>
            <p class="card-text">Текст: {{ object.content|truncatechars:100 }}</p>
            <p class="card-text">К-во просмотров: {{ object.number_of_views }}</p>
            <p class="card-text">Дата записи: {{ object.date_of_publication }}</p>
            <p class="card-text">Опубликовано: {{ object.is_active }}</p>
            <!--Этой строкой для единообразия выводимых карточек отображаемое описание ограничивается 100 символами.-->
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a class="btn btn-primary" href="{% url 'blog:blog_update' object.pk %}"
                       role="button">Редактировать</a>
                    <a class="btn btn-primary" href="{% url 'blog:blog_detail' object.pk %}"
                       role="button">Посмотреть</a>
                    <a class="btn btn-primary" href="{% url 'blog:blog_delete' object.pk %}" role="button">Удалить</a>
                </div>
                <small class="text-body-secondary">Не будем вычислять тебя по айпи</small>
                {% if user.is_authenticated %}
                {% if blog.is_active %}
                <a class="btn btn-warning" href="{% url 'blog:toggle_activity' object.pk %}">Снять с публикации</a>
                {% else %}
                <a class="btn btn-success" href="{% url 'blog:toggle_activity' object.pk %}">Опубликовать</a>
                {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endfor %}